[2025-07-16T23:56:49.490-0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data manual__2025-07-16T23:45:56.311266+00:00 [queued]>
[2025-07-16T23:56:49.542-0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data manual__2025-07-16T23:45:56.311266+00:00 [queued]>
[2025-07-16T23:56:49.543-0700] {taskinstance.py:1359} INFO - Starting attempt 5 of 2
[2025-07-16T23:56:49.669-0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): fetch_policy_data> on 2025-07-16 23:45:56.311266+00:00
[2025-07-16T23:56:49.682-0700] {standard_task_runner.py:57} INFO - Started process 19727 to run task
[2025-07-16T23:56:49.758-0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gdpr_ccpa_risk_pipeline', 'fetch_policy_data', 'manual__2025-07-16T23:45:56.311266+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/gdpr_ccpa_risk_pipeline.py', '--cfg-path', '/var/folders/qv/gh2d3t7x7xqgkvbl149fblxr0000gn/T/tmp2hp0vsq4']
[2025-07-16T23:56:49.800-0700] {standard_task_runner.py:85} INFO - Job 34: Subtask fetch_policy_data
[2025-07-16T23:56:50.415-0700] {task_command.py:415} INFO - Running <TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data manual__2025-07-16T23:45:56.311266+00:00 [running]> on host amritas-macbook-pro.local
[2025-07-16T23:56:50.897-0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='gdpr_ccpa_risk_pipeline' AIRFLOW_CTX_TASK_ID='fetch_policy_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T23:45:56.311266+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-16T23:45:56.311266+00:00'
[2025-07-17T01:03:54.698-0700] {process_utils.py:131} INFO - Sending 15 to group 19727. PIDs of all processes in the group: [19727]
[2025-07-17T01:03:56.838-0700] {process_utils.py:86} INFO - Sending the signal 15 to group 19727
[2025-07-17T01:04:56.884-0700] {process_utils.py:149} WARNING - process psutil.Process(pid=19727, name='python3.11', status='running', started='23:56:49') did not respond to SIGTERM. Trying SIGKILL
[2025-07-17T01:04:59.434-0700] {process_utils.py:86} INFO - Sending the signal 9 to group 19727
[2025-07-17T01:05:01.140-0700] {process_utils.py:79} INFO - Process psutil.Process(pid=19727, name='python3.11', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='23:56:49') (19727) terminated with exit code -9
[2025-07-17T01:05:01.349-0700] {standard_task_runner.py:172} ERROR - Job 34 was killed before it finished (likely due to running out of memory)
